Update and correct README.md
Pronovix/swagger_ui_formatter pull request #47
Opened 2020-10-27 15:09 UTC by balazswmann

Closes #36

2020-11-16 06:24 UTC, mxr576 requested changes

2020-11-16 06:24 UTC, mxr576 commented on README.md
> +[Composer template for Drupal projects](https://github.com/drupal-composer/drupal-project)
Not nowadays :) Let's reference this one: https://packagist.org/packages/drupal/recommended-project

2020-11-16 06:24 UTC, mxr576 commented on README.md
> +**Note:** If the content of the Swagger file does not render correctly try
Let's move this to a new `## Troubleshooting` section.

2020-11-16 06:24 UTC, mxr576 commented on README.md
> +caches" button.
We should also suggest checking the Status page for reported issues by Swagger UI FF.

2020-11-16 06:26 UTC, mxr576 commented on README.md
> +From version `8.x-2.x` the Swagger UI library needs to be installed separately.
Since we are at 3.x, I am not sure if this information is still relevant since the preferred way of installing Swagger UI is also described in a few sentences below. (Or I would add this information to that section without the version reference, like "Swagger UI library needs to ....")

2020-11-16 08:20 UTC, balazswmann commented on README.md
> +[Composer template for Drupal projects](https://github.com/drupal-composer/drupal-project)
Thanks, corrected.

2020-11-16 08:20 UTC, balazswmann commented on README.md
> +**Note:** If the content of the Swagger file does not render correctly try
Thanks, corrected.

2020-11-16 08:21 UTC, balazswmann commented on README.md
> +caches" button.
I extended the section with this information too.

2020-11-16 08:22 UTC, balazswmann commented on README.md
> +From version `8.x-2.x` the Swagger UI library needs to be installed separately.
I agree. First I just removed the section but then I replaced the content with some information about the minimum supported library version.

2020-11-19 06:48 UTC, mxr576 submitted a review, later dismissed

2020-11-19 09:43 UTC, mxr576 approved these changes

2020-11-19 12:32 UTC, merged