[#49] Update dependencies
Pronovix/swagger_ui_formatter pull request #51
Opened 2020-11-09 00:48 UTC by VladimirAus

Addresses: 

* Installation with Drupal 9.0.
* #49 Update pronovix/* dependencies to 2.11
* #50 Composer 2 compatibility

2020-11-09 08:02 UTC, mxr576 requested changes
@VladimirAus Thanks for your contribution! 
Can you please also fix reported issues by the update Coder? (See Travis CI)

2020-11-09 08:02 UTC, mxr576 commented on composer.json
> +        "drupal/core-recommended": "^8.9.1 || ^9"
I am not sure why changing the original constraint are required, can you elaborate?

We prefer `~` over `^` because we saw a tendency that new minor Drupal core updates have broken downstream projects and contrib modules in the past (even there is a BC promise). Because of that, without validating compatibility with an upcoming Drupal core (minor) release, it does not seem a good idea allowing _any_ component to be installed on any Drupal core minor release.

When 9.1.0 is out (or the RC1) we can easily extend our test suite to check compatibility with that too.

2020-11-09 14:26 UTC, VladimirAus commented on composer.json
> +        "drupal/core-recommended": "^8.9.1 || ^9"
@mxr576 Drupal 9.1 beta is out and I'm already testing my projects in order to go live in December. 🎄 

Minor core projects didn't break anything for me for the last 3 years. It might be something to do with the technique called testing before upgrading production. 😉

2020-11-09 14:46 UTC, mxr576 commented on composer.json
> +        "drupal/core-recommended": "^8.9.1 || ^9"
Well, then you are one of the lucky ones :) (Ofc, we also haven't break production with an update ;P )

> I'm already testing my projects in order to go live in December.

Leaving on the edge is not the safest :)

> testing before upgrading
This is exactly what I am recommending here ;) let's test and confirm 9.1 compatibilities (automatically) before we would just simply allow the module to be installed on 9.1. (Let's prevent the blame-train to leave the station when someone just installs the module and it breaks things... "why the hell you marked it compatible when it does not?!")

So if you wish to add 9.1 compatibility, please create a separate PR with that which also extends the automated test coverage in Travis for that Drupal (minor) version. The current test suite only tests with 9.0.x latest - even after your changes: https://travis-ci.org/github/Pronovix/swagger_ui_formatter/jobs/742321750#L852.

2020-11-09 14:49 UTC, mxr576 commented
This PR would only resolve #50 if the automated test suite would start using Composer 2 by default.

2020-11-09 14:50 UTC, mxr576 commented on composer.json
>          "oomphinc/composer-installers-extender": "^1.1",
Composer 2 compatibility is only available since ^2.0

2020-11-09 14:50 UTC, mxr576 commented on composer.json
>          "composer/installers": "^1.6",
Composer 2 compatibility is only available since ^1.8

2020-11-16 06:17 UTC, mxr576 commented
@VladimirAus We have merged a fix that addresses only #49 so we can wrap up all blockers for 3.0, please continue the work here to resolve #52 if you still feel that a priority. Thank you

2023-03-27 10:13 UTC, mxr576 commented
These are addressed by #90.

2023-03-27 10:13 UTC, closed without merging