Fix post update hook to rebuild cache due to implementation changes
Pronovix/swagger_ui_formatter pull request #57
Opened 2020-11-20 13:45 UTC by balazswmann

2020-11-23 07:30 UTC, mxr576 requested changes

2020-11-23 07:30 UTC, mxr576 commented on swagger_ui_formatter.post_update.php
> +  drupal_flush_all_caches();
An empty post-update hook should also warrant that caches are cleared, so it is not enough?
I think flushing all caches after updates should be also a generic final step of automated deployments because without that multiple things can be broken like outdated CSS/JS can be served for users.
(I have also checked a considerable huge codebase and I have also seen two occurrences of calling `drupal_flush_all_caches()`in an update hook - besides this module - and I am not even sure that those calls were actually necessary either.)

(Plus I am not sure if this module should display any message unless the message is displayed like "Swagger UI FF: All cache...", displaying just "All cache..." would be confusing)

2020-11-23 08:09 UTC, balazswmann commented on swagger_ui_formatter.post_update.php
> +  drupal_flush_all_caches();
Ok, so what's your suggestion? I have already did some testing and without calling `drupal_flush_all_caches();` directly the new library discovery service is not found during the first `drush cr`.

2020-11-23 08:12 UTC, balazswmann commented on swagger_ui_formatter.post_update.php
> +  drupal_flush_all_caches();
We could be less general with a services related cache clear, so we wouldn't have to clear everything. But even then, it can happen that the cache clear will conflict with some other module's update hook if they are working with services for example.

2020-11-23 08:35 UTC, balazswmann commented on swagger_ui_formatter.post_update.php
> +  drupal_flush_all_caches();
So I think there are 3 things we should decide about before we could move on:

1. As it turned out, and empty post update hook doesn't clear all the caches correctly or it doesn't clear caches at all. Knowing this, the question comes up: should we keep our previous post update hooks or not?

All update hooks we had so far were about cache clear or they were intended to clear cache. So theoretically it doesn't matter whether you run the cache clear 3 times (someone coming from a very old version) or just 1 time (coming from `8.x-2.4`). Especially if the cache doesn't get cleared for the first 2 times correctly.

2. An empty post update hook in itself won't be enough. Should we clear all the caches via `drupal_flush_all_caches();` or should be more specific and clear only the services related cache somehow? Even in the latter case it can happen that the cache clear will conflict with some other modules' update hook if they are working with cached services related data for example.

3. Should we return with any message in the post update hook? If so what should be the message exactly? The hook related description from its function documentation will be displayed anyway, so perhaps that's enough. Should we change that text too?

2020-11-24 06:16 UTC, mxr576 commented on swagger_ui_formatter.post_update.php
> +  drupal_flush_all_caches();
> As it turned out, and empty post update hook doesn't clear all the caches correctly or it doesn't clear caches at all.

It clear caches, but it does not rebuild the service container - which is also cached ofc, but it is not a cache clear issue - this is the reason why the new service is not registered yet when `drush cr` runs, I think.

> or we should be more specific and clear only the services related cache somehow?

There is a hacky way to do that but I would not go that far because who knows what gets broken if our one update hooks rebuild service definitions when it should not... I would rather investigate the following:

> Ok, so what's your suggestion? I have already did some testing and without calling drupal_flush_all_caches(); directly the new library discovery service is not found during the first drush cr.

Does it happens because `swagger_ui_formatter_cache_flush()` exists? Maybe we should add a trap condition there with a comment and only call the service if it exists.

> Should we return with any message in the post update hook?

As far as I have seen, only for flushing caches, no message used to be returned by post-update hooks. (Usually, no message is returned by them)

2020-11-24 20:16 UTC, balazswmann commented on swagger_ui_formatter.post_update.php
> +  drupal_flush_all_caches();
Ok, thanks for the feedback. I modified `swagger_ui_formatter_cache_flush()` and did a quick test, it looks good. Let's see what the CI says.

2020-11-30 07:11 UTC, mxr576 commented on swagger_ui_formatter.module
> +  if (\Drupal::hasService('swagger_ui_formatter.swagger_ui_library_discovery')) {
Nitpicks only:
* I would extract the name of the service to a new variable - making sure that we are not making a typo accidentally :)
* Leave a TODO above the condition that it can be removed in 4.x .

2020-11-30 07:11 UTC, mxr576 approved these changes

2020-11-30 14:43 UTC, balazswmann commented on swagger_ui_formatter.module
> +  if (\Drupal::hasService('swagger_ui_formatter.swagger_ui_library_discovery')) {
Thanks, I committed the fixes.

2020-11-30 14:44 UTC, mxr576 approved these changes

2020-12-01 07:10 UTC, merged